name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master]

jobs:
  deployment:
    runs-on: [ 'self-hosted', 'Linux', 'X64']
    environment: production
    steps:
      - name: Deploying
        run: /opt/pybot.sh